[
{"Descripcion" : "QUIEN ES DIOS ?","citaBiblica" : "JUAN 3:16","Libro" : "1","Respuestas" : [{ "respuesta" : "El creador del universo", "esLaCorrecta" : true },{ "respuesta" : "El dios del mal", "esLaCorrecta" : false },{ "respuesta" : "el hijo de adan", "esLaCorrecta" : false },{ "respuesta" : "el hijo de abraham", "esLaCorrecta" : false }]},
{"Descripcion" : "QUIEN ES LUCIFER ?","citaBiblica" : "JUAN 3:17","Libro" : "1","Respuestas" : [{ "respuesta" : "El angel caido", "esLaCorrecta" : true },{ "respuesta" : "El creador del universo", "esLaCorrecta" : false },{ "respuesta" : "el hijo de adan", "esLaCorrecta" : false },{ "respuesta" : "el hijo de abraham", "esLaCorrecta" : false }]},
{"Descripcion" : "PRIMER NOMBRE QUE APARECE EN EL LIBRO DE HECHOS","citaBiblica" : "HECHOS 1: 1","Libro" : "2","Respuestas" : [{ "respuesta" : "Teofilo", "esLaCorrecta" : true },{ "respuesta" : "Pablo", "esLaCorrecta" : false },{ "respuesta" : "Juan", "esLaCorrecta" : false },{ "respuesta" : "Jacono", "esLaCorrecta" : false }]},
{"Descripcion" : "¿CUANTOS DÍAS ESTUVO JESÚS CON LOS DISCÍPULOS DESPUÉS DE SU RESURRECCIÓN? ","citaBiblica" : "HECHOS 1: 3","Libro" : "2","Respuestas" : [{ "respuesta" : "40 dias", "esLaCorrecta" : true },{ "respuesta" : "25 dias", "esLaCorrecta" : false },{ "respuesta" : "10 dias", "esLaCorrecta" : false },{ "respuesta" : "41 dias", "esLaCorrecta" : false }]},
{"Descripcion" : "¿QUE RECIBIREMOS CUANDO VENGA SOBRE NOSOTROS EN ESPÍRITU SANTO?","citaBiblica" : "HECHOS 1: 8","Libro" : "2","Respuestas" : [{ "respuesta" : "Recibiremos poder", "esLaCorrecta" : true },{ "respuesta" : "Recibiremos gloria", "esLaCorrecta" : false },{ "respuesta" : "Recibiremos ayuda", "esLaCorrecta" : false },{ "respuesta" : "Recibiremos dinero", "esLaCorrecta" : false }]},
{"Descripcion" : "DESPUÉS QUE JESÚS HABÍA RESUCITADO ¿DE QUE LES HABLABA A LOSAPÓSTOLES?","citaBiblica" : "HECHOS 1:3","Libro" : "2","Respuestas" : [{ "respuesta" : "Del reino de Dios", "esLaCorrecta" : true },{ "respuesta" : "Del dinero", "esLaCorrecta" : false },{ "respuesta" : "De las obras", "esLaCorrecta" : false },{ "respuesta" : "De la fe", "esLaCorrecta" : false }]},
{"Descripcion" : "¿DENTRO DE CUANTO TIEMPO LES DIJO JESÚS A SUS DISCÍPULOS QUE SERIAN BAUTIZADOS POR EL ESPÍRITU SANTO?","citaBiblica" : "HECHOS 1:5","Libro" : "2","Respuestas" : [{ "respuesta" : "Dentro de no muchos dias", "esLaCorrecta" : true },{ "respuesta" : "En una semana", "esLaCorrecta" : false },{ "respuesta" : "En un año despues", "esLaCorrecta" : false },{ "respuesta" : "Por la tarde", "esLaCorrecta" : false }]},
{"Descripcion" : "¿QUIENES SE LES APARECIERON A LOS DISCÍPULOS CUANDO JESUS ESTABA ASCENDIENDO AL CIELO?","citaBiblica" : "HECHOS 1:10","Libro" : "2","Respuestas" : [{ "respuesta" : "2 Varones con vestiduras blancas", "esLaCorrecta" : true },{ "respuesta" : "Gabriel y Jacobo", "esLaCorrecta" : false },{ "respuesta" : "Moises y Elias", "esLaCorrecta" : false },{ "respuesta" : "Salomon y David", "esLaCorrecta" : false }]},
{"Descripcion" : "¿EN QUE FUE ALZADO JESÚS?","citaBiblica" : "HECHOS 1:9","Libro" : "2","Respuestas" : [{ "respuesta" : "En una nube", "esLaCorrecta" : true },{ "respuesta" : "En un viento", "esLaCorrecta" : false },{ "respuesta" : "En un carro de fuego", "esLaCorrecta" : false },{ "respuesta" : "En dos nubes", "esLaCorrecta" : false }]},
{"Descripcion" : "¿CUANTOS ERAN LOS REUNIDOS EN EL APOSENTO?","citaBiblica" : "HECHOS 1:15","Libro" : "2","Respuestas" : [{ "respuesta" : "120", "esLaCorrecta" : true },{ "respuesta" : "12", "esLaCorrecta" : false },{ "respuesta" : "3000", "esLaCorrecta" : false },{ "respuesta" : "150", "esLaCorrecta" : false }]},
{"Descripcion" : "¿COMO SE LLAMA EL CAMPO DONDE MURIÓ JUDAS?","citaBiblica" : "HECHOS 1:19","Libro" : "2","Respuestas" : [{ "respuesta" : "Acéldama", "esLaCorrecta" : true },{ "respuesta" : "Campo de luz", "esLaCorrecta" : false },{ "respuesta" : "Rancho Judas", "esLaCorrecta" : false },{ "respuesta" : "Campo de traicion", "esLaCorrecta" : false }]},
{"Descripcion" : "¿QUIEN FUE EL SUSTITUTO DE JUDAS?","citaBiblica" : "HECHOS 1:26","Libro" : "2","Respuestas" : [{ "respuesta" : "Matias", "esLaCorrecta" : true },{ "respuesta" : "Jacobo", "esLaCorrecta" : false },{ "respuesta" : "Pedro", "esLaCorrecta" : false },{ "respuesta" : "Zaqueo", "esLaCorrecta" : false }]}
]
